### ISSUE TITLE
GUI Issue - Dark Theme - Performance Details

### ISSUE THREAD

**Issue by BeastleeUK** [memphisx/netcheck-frontend#77]
Frontend Version: 0.8.1
Backend Version: 0.10.3
Hosting Method: Docker

Issue: When viewing the performance details of a domain with the dark theme enabled the theme isn't applying to the popup under the burger selector, this makes it very difficult to read the text.

Example:
![image](https://user-images.githubusercontent.com/18753419/115142421-94811680-a039-11eb-9779-3c41bec2bf81.png)

**Comment by memphisx** [comment]
@BeastleeUK this is fixed now on the 0.8.2 version of the frontend. Please feel free to open a new ticket if you find any other issues.

**Comment by BeastleeUK** [comment]
> @BeastleeUK this is fixed now on the 0.8.2 version of the frontend. Please feel free to open a new ticket if you find any other issues.

Thanks, I've updated my docker instance and it's looking great.  Keep up the great work.
